# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: trusty
sudo: required
os:
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false
branches:
  only: master
matrix:
  allow_failures:
    - julia: nightly

before_install:
  - mkdir -p $HOME/locomotion
  - git clone --depth=1 https://github.com/RobotLocomotion/drake.git $HOME/locomotion/drake-distro
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.checkout("RigidBodyDynamics"); Pkg.build("RigidBodyTreeInspector"); Pkg.test("RigidBodyTreeInspector"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("RigidBodyTreeInspector")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
