# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: trusty
sudo: required
os:
  - linux
julia:
  - 0.5
  - nightly
notifications:
  email: false
branches:
  only: master

before_install:
  - mkdir -p $HOME/locomotion
  - git clone --depth=1 https://github.com/RobotLocomotion/drake.git $HOME/locomotion/drake-distro
after_success:
  - julia -e 'cd(Pkg.dir("RigidBodyTreeInspector")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
